#pragma once

#define EE_HANDS

#define TAPPING_TERM 250
#define PERMISSIVE_HOLD
#define FLOW_TAP_TERM 150
#define CHORDAL_HOLD
#define SPECULATIVE_HOLD

#define MOUSEKEY_INTERVAL    5
#define MOUSEKEY_MOVE_DELTA  2
#define MOUSEKEY_TIME_TO_MAX 120

#define MOUSEKEY_WHEEL_INTERVAL    20
#define MOUSEKEY_WHEEL_MAX_SPEED   2
#define MOUSEKEY_WHEEL_TIME_TO_MAX 160
